### ISSUE TITLE
Rats crash in 1.16.3

### ISSUE THREAD

**Issue by Nubidubi23** [Alex-the-666/Rats#440]
![unknown](https://user-images.githubusercontent.com/48162191/95654797-24825880-0b0b-11eb-9e9c-eee51b2dacf5.png)

Every time i try to use the rats mod in 1.16.3 i get that error

**Comment by AlexModGuy** [comment]
fixed

**Comment by Sixdd6** [comment]
This is either still a problem or a new problem with the same error has occurred for me.
[crash-2020-11-23_09.50.34-fml.txt](https://github.com/Alex-the-666/Rats/files/5584121/crash-2020-11-23_09.50.34-fml.txt)

Minecraft: 1.16.3
Forge: 34.1.42
Rats: 7.0.1
