### ISSUE TITLE
Rat Miner and Rat Quarry not working

### ISSUE THREAD

**Issue by CrazedBot37** [Alex-the-666/Rats#722]
I added the rat Miner upgrade to my rat, it seemed to work, but it was incapable of mining stone, it also was unable to pathfind to the deposit container. Even though it could detect ores, it was unable to get to them. It is worth noting that I'm using the Miner upgrade, NOT the Advanced Miner upgrade, as I know that it has the ability to specify what it breaks. Next, I have 2 Quarry rats, they can mine and deposit normally, but when the Quarry block gets too high for them to deposit, they are supposed to climb up using the rat quarry platform blocks right? Well, they are unable to use those, they just sit there... helpless. Mod developers, please fix this. One last thing, one of my friends tried using a rat with replanted and assigned it to harvest his wheat, it kept teleporting up to the surface, (his farm was underground) but he didn't have an ender upgrade, but it kept teleporting to the surface, and kept drowning in a pond nearby in an attempt to harvest the tall grass? Also, I should also add that I don't think that rats can't swim, if this in an intended feature let me know, but seriously, if a tamed rat has the chance, it seems to pathfind/teleport to water and end it's suffering,no joke, so please... please fix this...

**Comment by EwanCooey** [comment]
Advance miner runs into issues too.  I'm using astral sorcery to create sand, and I set the rat to only mine sand, it ran off to harvest grass instead.

**Comment by GizmoTheMoonPig** [comment]
Fixed in 5e5583927d7cc0727b0c8dbb162f274c0380c77e

**Comment by tokinmew** [comment]
idk what you mean by this is fixed, theyre still bugging out constantly for me. if i have one rat mining itll work down about 3 or 4 layers before being completely confused and eventually just standing around until i remove a block from their hand, then theyll mine one block, take it to the quarry, and then break again. if i have more then one rat i cant assign the others to any other quarry and they wont work on the same one that the first one was working on.

**Comment by tokinmew** [comment]
using Roguelike adventures and dungeons 2 modpack via curseforge and made sure it was updated

**Comment by TheViralDivinity** [comment]
Yeah this is not fixed.. Rats as a whole seem overall buggy, especially when playing multiplayer. Last I remember, multiple rat upgrades / interactions don't work properly or at all on a multiplayer world for whatever reason.

When I so much as tell a rat to take cheese from the curdling station he doesn't. Just sits there, forever.
